In [3]:
from PIL import Image

In [15]:
image = Image.open("image_0001.jpg")

In [18]:
image = image.resize((8, 8), Image.ANTIALIAS)  # Reduce it's size.

In [19]:
image = image.convert("L")  # Convert it to grayscale.

In [20]:
pixels = list(image.getdata())

In [21]:
print(pixels)

[0, 148, 232, 151, 127, 112, 1, 0, 156, 194, 103, 101, 93, 120, 103, 14, 138, 42, 17, 77, 45, 45, 117, 153, 87, 56, 23, 20, 38, 17, 60, 114, 178, 83, 51, 36, 25, 50, 79, 63, 163, 182, 91, 41, 23, 10, 51, 66, 9, 127, 171, 80, 25, 11, 35, 85, 0, 0, 106, 166, 80, 134, 90, 6]


In [22]:
import os, sys
import PIL
import numpy
from datasketch import MinHash, MinHashLSH
from PIL import Image

In [45]:
img = Image.open("image_0001.jpg").convert('LA').resize((10,10), PIL.Image.ANTIALIAS)
numpy_array = numpy.array(img)
# print(numpy_array)

[[[  0 255]
  [ 38 255]
  [227 255]
  [221 255]
  [157 255]
  [120 255]
  [145 255]
  [ 24 255]
  [  0 255]
  [  4 255]]

 [[ 66 255]
  [232 255]
  [198 255]
  [112 255]
  [106 255]
  [111 255]
  [110 255]
  [132 255]
  [ 25 255]
  [  0 255]]

 [[202 255]
  [139 255]
  [ 16 255]
  [ 87 255]
  [ 91 255]
  [ 66 255]
  [ 80 255]
  [113 255]
  [142 255]
  [ 71 255]]

 [[ 96 255]
  [ 55 255]
  [ 35 255]
  [  6 255]
  [ 71 255]
  [ 39 255]
  [ 16 255]
  [ 54 255]
  [113 255]
  [178 255]]

 [[109 255]
  [ 61 255]
  [ 45 255]
  [ 19 255]
  [ 18 255]
  [ 48 255]
  [ 15 255]
  [ 38 255]
  [ 72 255]
  [103 255]]

 [[175 255]
  [ 98 255]
  [ 56 255]
  [ 45 255]
  [ 30 255]
  [ 21 255]
  [ 46 255]
  [ 75 255]
  [ 65 255]
  [ 73 255]]

 [[198 255]
  [173 255]
  [ 99 255]
  [ 70 255]
  [ 46 255]
  [ 31 255]
  [  7 255]
  [ 38 255]
  [ 98 255]
  [ 40 255]]

 [[ 55 255]
  [180 255]
  [187 255]
  [ 87 255]
  [ 37 255]
  [ 18 255]
  [ 25 255]
  [  1 255]
  [ 27 255]
  [ 98 255]]

 [[  0 255]
  [ 29 255]


In [65]:
from datasketch import MinHashLSHForest, MinHash

img1 = Image.open("image_0001.jpg").convert('LA').resize((10,10), PIL.Image.ANTIALIAS)
img2 = Image.open("image_0002.jpg").convert('LA').resize((10,10), PIL.Image.ANTIALIAS)
img3 = Image.open("image_0001.jpg").convert('LA').resize((10,10), PIL.Image.ANTIALIAS)

data1 = numpy.array(img1)
data2 = numpy.array(img2)
data3 = numpy.array(img3)


# Create MinHash objects
m1 = MinHash(num_perm=128)
m2 = MinHash(num_perm=128)
m3 = MinHash(num_perm=128)
for d in data1:
    m1.update(d)
for d in data2:
    m2.update(d)
for d in data3:
    m3.update(d)

forest = MinHashLSHForest(num_perm=128)

# Add m2 and m3 into the index
forest.add("m2", m2)
forest.add("m3", m3)

# IMPORTANT: must call index() otherwise the keys won't be searchable
forest.index()

# Check for membership using the key
print("m2" in forest)
print("m3" in forest)

# Using m1 as the query, retrieve top 2 keys that have the higest Jaccard
result = forest.query(m1, 2)
print("Top 2 candidates", result)

True
True
Top 2 candidates ['m3']
